services:
  app:
    container_name: application
    build: .
    networks:
      - app-network
    ports:
      - "9111:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: mysql
    image: mysql:latest
    environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=test
            - MYSQL_USER=saleh
            - MYSQL_PASSWORD=password
    volumes:
      - db-volume:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -P 3306 --protocol=TCP -usaleh -ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app-network

networks:
  app-network:

volumes:
  db-volume:
