name: Code Quality
on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  QA:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: make env file
        run: cp .env.example .env

      - name: spin container
        run: docker compose up -d

      - name: generate app key
        run: docker exec application php artisan key:generate

      - name: run tests
        run: docker exec application php artisan test

      - name: run static analysis
        run: docker exec application ./vendor/bin/phpstan analyse -l 6 app

      - name: install and enable xdebug
        run: |
          docker exec application pecl install xdebug
          docker exec application docker-php-ext-enable xdebug

      - name: run coverage
        run: docker exec -e XDEBUG_MODE=coverage application php artisan test --coverage
