name: Code Quality

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  
jobs:
  Testing:
      runs-on: ubuntu-latest

      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: make env file
          run: cp .env.example .env

        - name: spin container
          run: docker compose -f compose.yml -f docker-compose.ci.yml up -d

        - name: generate app key
          run: docker exec application php artisan key:generate
          
        - name: install dev dependencies
          run: docker exec application composer install --no-interaction --prefer-dist --optimize-autoloader
          
        - name: run test
          run: docker exec application php artisan test

        - name: set xdebug
          run: |
              docker exec application pecl install xdebug
              docker exec application docker-php-ext-enable xdebug
            
        - name: run covarge check
          run:  docker exec -e XDEBUG_MODE=coverage application php artisan test --coverage

  Static_Analysis: 
    runs-on: ubuntu-latest
    needs: Testing
    
    steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: make env file
          run: cp .env.example .env

        - name: spin container
          run: docker compose -f compose.yml -f docker-compose.ci.yml up -d

        - name: install dev dependencies
          run: docker exec application composer install --no-interaction --prefer-dist --optimize-autoloader
          
        - name: static code analysis
          run: docker exec application ./vendor/bin/phpstan analyse -l 6 app
