name: Code Quality

on:
  pull_request:
    branches:
      - dev
      - main
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  
jobs:
  QA:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
          
        - name: make env file
          run:  cp .env.example .env
          
        - name: spin container
          run:  docker compose up -d
          
        - name: generate app key
          run:  docker exec application php artisan key:generate
          
        - name: run test
          run:  docker exec application php artisan test
          
        - name: run static analysis
          run:  docker exec application ./vendor/bin/phpstan analyse -l 6 app
          
        - name: install x-debug
          run:  docker exec application  pecl install xdebug
          
        - name: run covarge check
          run:  docker exec -e XDEBUG_MODE=coverage application php artisan test --coverage
